# 1. Normalization Problem

In [1]:
#Normalization Problem

In [3]:
#importing numpy
import numpy as np

In [4]:
#Creating a random 5 x 5 ndarray
X = np.random.random((5,5))
X

array([[0.01480882, 0.62142521, 0.70952956, 0.56256514, 0.42261103],
       [0.40066664, 0.96951246, 0.24967853, 0.89433822, 0.46219975],
       [0.25611114, 0.82263064, 0.03929618, 0.52869062, 0.60611145],
       [0.26860599, 0.90744439, 0.84467425, 0.79398915, 0.03453855],
       [0.38114928, 0.48020624, 0.7928646 , 0.94518191, 0.75845552]])

In [7]:
#Finding the Mean of the random elements
m = np.mean(X)
m

0.5506914109692215

In [9]:
#Finding the Standard Dev. of the random elements
s = np.std(X)
s

0.28873768461918203

In [11]:
#Normalizing the random elements using the formula: Z=(X-m)/s
Z = ((X-m)/s)
Z

array([[-1.85594959,  0.24497599,  0.5501123 ,  0.0411229 , -0.44358733],
       [-0.51958848,  1.45052436, -1.04251331,  1.19016957, -0.30647768],
       [-1.02023494,  0.94182106, -1.77114127, -0.07619646,  0.19193905],
       [-0.97696089,  1.23556085,  1.01816582,  0.84262552, -1.78761863],
       [-0.58718395, -0.2441149 ,  0.8387308 ,  1.36625912,  0.71956008]])

In [13]:
#Saving the result as X_normalized.npy
np.save('X_normalized', Z)

In [ ]:
#End of Code

# 2. Divisible By 3 Problem

In [15]:
#Divisible By 3 Problem

In [17]:
#importing numpy
import numpy as np

In [19]:
#Generating the ndarray
A = np.arange(1,101).reshape(10,10)
A = np.square(A)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [21]:
#Filtering the elements divisible by 3
B = A[A % 3 == 0]
B

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [23]:
#Saving the result as div_by_3.npy
np.save('div_by_3', B)

In [25]:
#End of Code