# 1. Normalization Problem

In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

### Importing numpy

In [1]:
#Normalization Problem

In [28]:
#importing numpy
import numpy as np

### Initializing the random 5x5 ndarray

In [30]:
#Creating a random 5 x 5 ndarray
X = np.random.random((5,5))
X

array([[0.17873752, 0.43035425, 0.13024452, 0.85888795, 0.00148741],
       [0.06755702, 0.19729975, 0.99230936, 0.00300311, 0.57867781],
       [0.26396834, 0.31057133, 0.96402417, 0.2772233 , 0.22352471],
       [0.48434997, 0.08997062, 0.48978752, 0.53962873, 0.4688475 ],
       [0.5567464 , 0.5904923 , 0.61257261, 0.81645498, 0.35939217]])

### Calculating for the Mean

In [32]:
#Finding the Mean of the random elements
m = np.mean(X)
m

0.419444535014256

### Calculating for the Standard Deviation

In [34]:
#Finding the Standard Dev. of the random elements
s = np.std(X)
s

0.2815709337041791

### Calculating for the Z

In [36]:
#Normalizing the random elements using the formula: Z=(X-m)/s
Z = ((X-m)/s)
Z

array([[-0.85487166,  0.03874589, -1.0270947 ,  1.56068457, -1.48437595],
       [-1.24972953, -0.78894784,  2.03453111, -1.47899293,  0.56551745],
       [-0.55217416, -0.38666352,  1.93407619, -0.50509913, -0.69580983],
       [ 0.23051185, -1.17012759,  0.24982333,  0.42683452,  0.17545476],
       [ 0.48762798,  0.60747665,  0.68589494,  1.40998375, -0.21327613]])

### Saving the result in a local .npy file

In [38]:
#Saving the result as X_normalized.npy
np.save('X_normalized', Z)

In [40]:
#End of Code

# 2. Divisible By 3 Problem

Create a 10 x 10 ndarray, which includes squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

### Importing numpy

In [15]:
#Divisible By 3 Problem

In [42]:
#importing numpy
import numpy as np

### Generating the given ndarray

In [44]:
#Generating the ndarray
A = np.arange(1,101).reshape(10,10)
A = np.square(A)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

### Filtering all values divisible by 3

In [46]:
#Filtering the elements divisible by 3
B = A[A % 3 == 0]
B

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

### Saving the result in a local .npy file

In [48]:
#Saving the result as div_by_3.npy
np.save('div_by_3', B)

In [25]:
#End of Code